# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-20 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(max_length=500)),
                ('bank_id', models.CharField(max_length=500)),
                ('branch', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('bank_name', models.CharField(max_length=500)),
            ],
        ),
    ]
